### ISSUE TITLE
Item price blank on negotiate popup

### ISSUE THREAD

**Issue by Archit404Error** [cuappdev/resell-react-native#93] opened 2024-03-15 23:42 UTC
When attempting to negotiate the price, it looks like the spot where the item price should be is blank:
![image](https://github.com/cuappdev/resell-react-native/assets/22649594/d73c7391-d646-49a2-abab-a84e2f3d71de)

In this case the price was supposed to be $25

**Comment by zachseidner1** [comment] 2024-03-20 22:24
Duplicate of #66

**Closed by zachseidner1** 2024-03-20 22:24 UTC
Labels: bug, duplicate
